# 全局配置
global:
  # 抓取时间周期，默认为1分钟，这里设置为15s
  scrape_interval: 15s

# 各个服务抓取配置
scrape_configs:
  - job_name: "node_exporter"
    static_configs:
{%- for host in groups['node_exporter'] %}
      - targets:
          - "{{ hostvars[host]['node_exporter_bind_host'] }}:{{ hostvars[host]['node_exporter_bind_port'] }}"
        labels:
          home: "{{ home_name }}"
          host: "{{ host }}"
{%- endfor %}

  - job_name: "cadvisor"
    static_configs:
{%- for host in groups['cadvisor'] %}
      - targets:
          - "{{ hostvars[host]['cadvisor_bind_host'] }}:{{ hostvars[host]['cadvisor_bind_port'] }}"
        labels:
          home: "{{ home_name }}"
          host: "{{ host }}"
{%- endfor %}

  - job_name: "process_exporter"
    static_configs:
{%- for host in groups['process_exporter'] %}
      - targets:
          - "{{ hostvars[host]['process_exporter_bind_host'] }}:{{ hostvars[host]['process_exporter_bind_port'] }}"
        labels:
          home: "{{ home_name }}"
          host: "{{ host }}"
{%- endfor %}

{%- for custom_scrape_config in service_vars.conf.custom_scrape_configs %}
  - {{ custom_scrape_config }}
{%- endfor %}

  - job_name: "my_exporter"
    static_configs:
{%- for host in groups['my_exporter'] %}
      - targets:
          - "{{ hostvars[host]['my_exporter_bind_host'] }}:{{ hostvars[host]['my_exporter_bind_port'] }}"
        labels:
          home: "{{ home_name }}"
          host: "{{ host }}"
{%- endfor %}

  - job_name: "nginx_vts_exporter"
    static_configs:
{%- for host in groups['nginx'] %}
      - targets:
          - "{{ hostvars[host]['nginx_vts_exporter_bind_host'] }}:{{ hostvars[host]['nginx_vts_exporter_bind_port'] }}"
        labels:
          home: "{{ home_name }}"
          host: "{{ host }}"
{%- endfor %}

  - job_name: "tailscale"
    static_configs:
{%- for host in groups['tailscale'] %}
      - targets:
          - "{{ hostvars[host]['tailscale_bind_host'] }}:{{ hostvars[host]['tailscale_bind_port'] }}"
        labels:
          home: "{{ home_name }}"
          host: "{{ host }}"
{%- endfor %}